### ISSUE TITLE
Error: Cannot find module 'intern-systemjs-loader'

### ISSUE THREAD

**Issue by indolering** [andyearnshaw/intern-systemjs-loader#4]
My intern.js config file seems to be setting off an error:

```
Error: Cannot find module 'intern-systemjs-loader'
  at Function.Module._resolveFilename  <module.js:469:15>
  at Function.resolve  <internal/module.js:27:19>
  at <tests/intern.js:36:59>
  at ContextifyScript.Script.runInThisContext  <vm.js:25:33>
  at Object.exports.runInThisContext  <vm.js:77:17>
  at <../../../../usr/lib/node_modules/intern/node_modules/dojo/loader.ts:838:14>
  at tryToString  <fs.js:455:3>
  at FSReqWrap.readFileAfterClose [as oncomplete]  <fs.js:442:12>
```

I ran `npm install systemjs-plugin-babel intern-systemjs-loader --save` multiple times and I am able to load them in regular Node scripts.

Here's the `intern.js` file:

```JS
// Learn more about configuring this file at <https://theintern.github.io/intern/#configuration>.
// These default settings work OK for most people. The options that *must* be changed below are the packages, suites,
// excludeInstrumentation, and (if you want functional tests) functionalSuites
define({
	// Default desired capabilities for all environments. Individual capabilities can be overridden by any of the
	// specified browser environments in the `environments` array below as well. See
	// <https://theintern.github.io/intern/#option-capabilities> for links to the different capabilities options for
	// different services.
	//
	// Note that the `build` capability will be filled in with the current commit ID or build tag from the CI
	// environment automatically
	capabilities: {
		'browserstack.selenium_version': '2.45.0'
	},

	// Browsers to run integration testing against. Options that will be permutated are browserName, version, platform,
	// and platformVersion; any other capabilities options specified for an environment will be copied as-is. Note that
	// browser and platform names, and version number formats, may differ between cloud testing systems.
	environments: [
		{ browserName: 'internet explorer', version: '11', platform: 'WIN8' },
		{ browserName: 'internet explorer', version: '10', platform: 'WIN8' },
		{ browserName: 'internet explorer', version: '9', platform: 'WINDOWS' },
		{ browserName: 'firefox', version: '37', platform: [ 'WINDOWS', 'MAC' ] },
		{ browserName: 'chrome', version: '39', platform: [ 'WINDOWS', 'MAC' ] },
		{ browserName: 'safari', version: '8', platform: 'MAC' }
	],

	// Maximum number of simultaneous integration tests that should be executed on the remote WebDriver service
	maxConcurrency: 2,

	// Name of the tunnel class to use for WebDriver tests.
	// See <https://theintern.github.io/intern/#option-tunnel> for built-in options
	tunnel: 'BrowserStackTunnel',

	loaders: {
		'host-node': require.nodeRequire && require.nodeRequire.resolve('intern-systemjs-loader'),
		'host-browser': 'node_modules/intern-systemjs-loader/main.js'
	},

	// Configuration options for the module loader; any AMD configuration options supported by the AMD loader in use
	// can be used here.
	// If you want to use a different loader than the default loader, see
	// <https://theintern.github.io/intern/#option-useLoader> for more information.
	loaderOptions: {
		// Packages that should be registered with the loader in each testing environment
		packages: [ { name: 'myPackage', location: '.' } ],

		loaderOptions: {
			transpiler: 'plugin-babel',

			map: {
				'plugin-babel': '/node_modules/systemjs-plugin-babel/plugin-babel.js',
				'systemjs-babel-build': '/node_modules/systemjs-plugin-babel/systemjs-babel-browser.js'
			}
		},

		excludeInstrumentation: true
	},

	// Unit test suite(s) to run in each browser
	suites: [ 'tests/unit/dns.js'/* 'myPackage/tests/foo', 'myPackage/tests/bar' */ ],

	// Functional test suite(s) to execute against each browser once unit tests are completed
	functionalSuites: [ /* 'myPackage/tests/functional' */ ],

	// A regular expression matching URLs to files that should not be included in code coverage analysis. Set to `true`
	// to completely disable code coverage.
	excludeInstrumentation: /^(?:tests|node_modules)\//
});
```

**Comment by andyearnshaw** [comment]
That's odd, I can't seem to repro.  What are your node/npm versions?  Here's what I did:
1. `npm init` in a new dir, test command is `intern-runner config=tests/local.intern`
2. `npm install --save-dev intern intern-systemjs-loader systemjs-plugin-babel`
3. `mkdir tests && vim tests/intern.js`, paste your sample file
4. `npm test`

Of course it fails because I don't use BrowserStack, but the configuration loads correctly and I don't see the same error.  Tested using Node 4, 5, 6 and 7.

**Comment by indolering** [comment]
I'm running it using `intern-client config=tests/intern` with intern-client installed as a global, could that be it?  What does your package.json look like?

**Comment by andyearnshaw** [comment]
yes, I suspect that could be the problem.  Why are you using intern-client as a global like that?  If you install intern locally, it's accessible as `intern-client` from your npm scripts (e.g. `npm test`).

**Comment by indolering** [comment]
> Why are you using intern-client as a global like that?

Because that's how Mocha recommends running their scripts, I just applied the same here : )

I've since moved away from SystemJS.  Will reopen if I run into the issue again.
